#!/bin/bash

set -euo pipefail

cd "$(dirname "$0")"

bash_scripts=(
    yank.tmux
    scripts/*.sh
)

set -x
docker run \
    --rm \
    --volume="${PWD}:/mnt:ro" \
    --workdir="/mnt" \
    bash:latest \
    bash -Dn "${bash_scripts[@]}"

docker run \
    --rm \
    --volume="${PWD}:/mnt:ro" \
    --workdir="/mnt" \
    koalaman/shellcheck:stable \
    --shell=bash \
    --external-sources \
    --color=always \
    "${bash_scripts[@]}"

# EOF
